---
title: "Untitled"
output: html_document
date: "2024-03-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  Loading Libraries
```{r}
library(tidyverse)
library(zoo)
library(gtrendsR)
library(ggplot2)
library(lubridate)
library(dplyr)
library(jsonlite)
library(httr)
```

##  Loading Datasets
```{r}
base_url <- "http://datamall2.mytransport.sg"

get_res_list <- function(endpoint) {
  res = GET(paste0(base_url, endpoint), 
            add_headers(AccountKey = Sys.getenv("LTA_KEY"),
                        accept = "application/json"))
  res_list <- content(res, type = "text", encoding = 'UTF-8') %>% 
    fromJSON(flatten = TRUE)
  return(res_list)
}
```

### Bus Services
```{r}
endpoint <- "/ltaodataservice/BusServices"
busServices <- as_tibble(get_res_list(endpoint)$value)
busServices
```

### Bus Routes
```{r}
endpoint <- "/ltaodataservice/BusRoutes"
busRoutes <- as_tibble(get_res_list(endpoint)$value)
busRoutes
```

### Bus Stops
```{r}
endpoint <- "/ltaodataservice/BusStops"
busRoutes <- as_tibble(get_res_list(endpoint)$value)
busRoutes
```

### Bus Arrival
Need to specify the bus stop code for each fetch.
```{r}
endpoint <- "/ltaodataservice/BusArrivalv2?BusStopCode=83139"
busArrival <- as_tibble(get_res_list(endpoint)$Services)
busArrival
```

### Taxi Availability
```{r}
endpoint <- "/ltaodataservice/Taxi-Availability"
taxiAvail <- get_res_list(endpoint)
taxiAvail
```


### Taxi Stands
```{r}
endpoint <- "/ltaodataservice/TaxiStands"
taxiStands <- get_res_list(endpoint)
taxiStands
```

### Estimated Travel Times
Returns estimated travel times (in minutes) of expressways (in segments)
```{r}
endpoint <- "/ltaodataservice/EstTravelTimes"
ETT <- get_res_list(endpoint)
ETT
```

